# Use postgres/example user/password credentials
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SAD_DB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
